/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import ASSETS.CellRender;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Enumeration;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author ByteDrive
 */
public class JFListarEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form JFShowEmpleados
     */
    public JFListarEmpleados() {
        initComponents();
     settingsFrame();
    }
    
    private void settingsFrame(){
         //Configuraciones jframe
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setSize(880, 610);
        this.getContentPane().setBackground(Color.black);
       
        //Set image in background panel
        JLabel backImage = new JLabel("");
        ImageIcon image = new ImageIcon(getClass().getResource("/ASSETS/carrr.jpg"));
        panel_image.add(backImage);
        backImage.setIcon(new ImageIcon(image.getImage().getScaledInstance(panel_image.getWidth()+30, panel_image.getHeight()+20,Image.SCALE_SMOOTH)));
        backImage.setSize(panel_image.getWidth()+30,panel_image.getHeight()+20);
        backImage.setLocation(0,0);
        
        //Set opacity showClientes panel
        Color color = new Color(255,255,255,200);
        panel_showEmpleados.setBackground(color);
        
        table_showEmpleados.setOpaque(false);
        table_showEmpleados.setBackground(null);
        cellRenderer(table_showEmpleados);
        this.table_showEmpleados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
         //Cambiar icono
        Image icon = Toolkit.getDefaultToolkit().getImage("/ASSETS/LogoCARSHOP.png");
        this.setIconImage(icon);
     
        
    }
    
    public void cellRenderer(JTable table){
        Enumeration<TableColumn> en = table.getColumnModel().getColumns();
        while(en.hasMoreElements()){
            TableColumn tc = en.nextElement();
            tc.setCellRenderer(new CellRender());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_image = new javax.swing.JPanel();
        panel_showEmpleados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_valueSearch = new javax.swing.JTextField();
        cbox_searchFor = new javax.swing.JComboBox();
        btn_search = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_showEmpleados = new javax.swing.JTable();
        btn_EditarEmpleado = new javax.swing.JLabel();
        btn_bajaEmpleado = new javax.swing.JLabel();
        btn_altaEmpleado = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mostrar empleados");

        jLabel1.setFont(new java.awt.Font("Neou", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPLEADOS");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Gulim", 0, 16)); // NOI18N
        jLabel2.setText("Buscar por:");

        cbox_searchFor.setBackground(java.awt.Color.lightGray);
        cbox_searchFor.setFont(new java.awt.Font("Gulim", 0, 16)); // NOI18N
        cbox_searchFor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Clave elector", "Nombre", "Tipo", "Todos" }));

        btn_search.setBackground(new java.awt.Color(51, 153, 255));
        btn_search.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/database22_1.png"))); // NOI18N
        btn_search.setText("Buscar");
        btn_search.setOpaque(true);

        table_showEmpleados.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        table_showEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_showEmpleados.setSelectionBackground(new java.awt.Color(153, 204, 255));
        table_showEmpleados.setShowGrid(false);
        jScrollPane2.setViewportView(table_showEmpleados);

        btn_EditarEmpleado.setBackground(new java.awt.Color(51, 153, 255));
        btn_EditarEmpleado.setFont(new java.awt.Font("Gulim", 0, 16)); // NOI18N
        btn_EditarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btn_EditarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/edit.png"))); // NOI18N
        btn_EditarEmpleado.setText("Editar");
        btn_EditarEmpleado.setIconTextGap(5);
        btn_EditarEmpleado.setOpaque(true);

        btn_bajaEmpleado.setBackground(new java.awt.Color(255, 102, 102));
        btn_bajaEmpleado.setFont(new java.awt.Font("Gulim", 0, 16)); // NOI18N
        btn_bajaEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btn_bajaEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/delete68.png"))); // NOI18N
        btn_bajaEmpleado.setText("Dar de baja");
        btn_bajaEmpleado.setOpaque(true);

        btn_altaEmpleado.setBackground(new java.awt.Color(84, 222, 66));
        btn_altaEmpleado.setFont(new java.awt.Font("Gulim", 0, 16)); // NOI18N
        btn_altaEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btn_altaEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/upload78.png"))); // NOI18N
        btn_altaEmpleado.setText("Dar de alta");
        btn_altaEmpleado.setOpaque(true);

        btn_cancelar.setBackground(new java.awt.Color(255, 102, 102));
        btn_cancelar.setFont(new java.awt.Font("Gulim", 0, 17)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.setOpaque(true);

        javax.swing.GroupLayout panel_showEmpleadosLayout = new javax.swing.GroupLayout(panel_showEmpleados);
        panel_showEmpleados.setLayout(panel_showEmpleadosLayout);
        panel_showEmpleadosLayout.setHorizontalGroup(
            panel_showEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_showEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_showEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_showEmpleadosLayout.createSequentialGroup()
                        .addGap(0, 206, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbox_searchFor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_valueSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(panel_showEmpleadosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(panel_showEmpleadosLayout.createSequentialGroup()
                .addGroup(panel_showEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_showEmpleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_showEmpleadosLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_showEmpleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_altaEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(btn_bajaEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_EditarEmpleado)))
                .addContainerGap())
        );
        panel_showEmpleadosLayout.setVerticalGroup(
            panel_showEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_showEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_showEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_showEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_showEmpleadosLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(txt_valueSearch))
                        .addComponent(cbox_searchFor)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_showEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_showEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_altaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_bajaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_showEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_EditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_imageLayout = new javax.swing.GroupLayout(panel_image);
        panel_image.setLayout(panel_imageLayout);
        panel_imageLayout.setHorizontalGroup(
            panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_imageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_showEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_imageLayout.setVerticalGroup(
            panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_imageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_showEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFListarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFListarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFListarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFListarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFListarEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_EditarEmpleado;
    public javax.swing.JLabel btn_altaEmpleado;
    public javax.swing.JLabel btn_bajaEmpleado;
    public javax.swing.JLabel btn_cancelar;
    public javax.swing.JLabel btn_search;
    public javax.swing.JComboBox cbox_searchFor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel_image;
    private javax.swing.JPanel panel_showEmpleados;
    public javax.swing.JTable table_showEmpleados;
    public javax.swing.JTextField txt_valueSearch;
    // End of variables declaration//GEN-END:variables
}
