/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author ByteDrive
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public JFLogin() {
        initComponents();
        settingsFrame();
    }

    
    private void settingsFrame(){
        //Configuraciones frame 
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setSize(338, 480);
        this.getContentPane().setBackground(new Color(255,102,102));
       
       
        //Set imageIcon logo CARSHOP
     
       ImageIcon imageLogo = new ImageIcon(getClass().getResource("/ASSETS/LogoCARSHOP.png"));
       label_image.setIcon(new ImageIcon(imageLogo.getImage().getScaledInstance(label_image.getWidth(),label_image.getHeight(),Image.SCALE_SMOOTH)));
      

        //Settings button
        btn_validarUser.setOpaque(false);
        btn_validarUser.setBackground(new Color(137,238,123));
        
        //JDIalog settings
        jDLogin_password.getContentPane().setBackground(new Color(255,102,102));
        
        btn_validarPassword.setOpaque(false);
        btn_validarPassword.setBackground(new Color(137,238,123));
        label_image1.setIcon(new ImageIcon(imageLogo.getImage().getScaledInstance(label_image.getWidth(),label_image.getHeight(),Image.SCALE_SMOOTH)));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDLogin_password = new javax.swing.JDialog();
        panel_backLogo1 = new javax.swing.JPanel();
        label_image1 = new javax.swing.JLabel();
        label_BienvenidoEmpelado = new javax.swing.JLabel();
        label_pass = new javax.swing.JLabel();
        btn_validarPassword = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        panel_backLogo = new javax.swing.JPanel();
        label_image = new javax.swing.JLabel();
        label_Bienvenido = new javax.swing.JLabel();
        label_Bienvenido1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        btn_validarUser = new javax.swing.JButton();

        jDLogin_password.setTitle("Validacion de contraseña");
        jDLogin_password.setPreferredSize(new java.awt.Dimension(338, 480));

        panel_backLogo1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout panel_backLogo1Layout = new javax.swing.GroupLayout(panel_backLogo1);
        panel_backLogo1.setLayout(panel_backLogo1Layout);
        panel_backLogo1Layout.setHorizontalGroup(
            panel_backLogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backLogo1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label_image1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        panel_backLogo1Layout.setVerticalGroup(
            panel_backLogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backLogo1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        label_BienvenidoEmpelado.setFont(new java.awt.Font("Walkway UltraExpand", 0, 24)); // NOI18N
        label_BienvenidoEmpelado.setForeground(new java.awt.Color(255, 255, 255));
        label_BienvenidoEmpelado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_BienvenidoEmpelado.setText("Bienvenido");

        label_pass.setFont(new java.awt.Font("Gulim", 0, 18)); // NOI18N
        label_pass.setForeground(new java.awt.Color(255, 255, 255));
        label_pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_pass.setText("Contraseña:");

        btn_validarPassword.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        btn_validarPassword.setForeground(new java.awt.Color(255, 255, 255));
        btn_validarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/password13.png"))); // NOI18N
        btn_validarPassword.setText("Validar");
        btn_validarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validarPasswordActionPerformed(evt);
            }
        });

        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout jDLogin_passwordLayout = new javax.swing.GroupLayout(jDLogin_password.getContentPane());
        jDLogin_password.getContentPane().setLayout(jDLogin_passwordLayout);
        jDLogin_passwordLayout.setHorizontalGroup(
            jDLogin_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_backLogo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDLogin_passwordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDLogin_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDLogin_passwordLayout.createSequentialGroup()
                        .addComponent(label_BienvenidoEmpelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDLogin_passwordLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jDLogin_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDLogin_passwordLayout.createSequentialGroup()
                                .addComponent(btn_validarPassword)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDLogin_passwordLayout.createSequentialGroup()
                                .addComponent(label_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
                            .addGroup(jDLogin_passwordLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(jDLogin_passwordLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );
        jDLogin_passwordLayout.setVerticalGroup(
            jDLogin_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDLogin_passwordLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panel_backLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_BienvenidoEmpelado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_validarPassword)
                .addGap(78, 78, 78))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_backLogo.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout panel_backLogoLayout = new javax.swing.GroupLayout(panel_backLogo);
        panel_backLogo.setLayout(panel_backLogoLayout);
        panel_backLogoLayout.setHorizontalGroup(
            panel_backLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backLogoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        panel_backLogoLayout.setVerticalGroup(
            panel_backLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backLogoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        label_Bienvenido.setFont(new java.awt.Font("Walkway UltraExpand", 0, 24)); // NOI18N
        label_Bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        label_Bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Bienvenido.setText("Bienvenido");

        label_Bienvenido1.setFont(new java.awt.Font("Gulim", 0, 18)); // NOI18N
        label_Bienvenido1.setForeground(new java.awt.Color(255, 255, 255));
        label_Bienvenido1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Bienvenido1.setText("Usuario:");

        txt_user.setFont(new java.awt.Font("Gulim", 0, 18)); // NOI18N
        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setToolTipText("Ingrese su usuario");

        btn_validarUser.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        btn_validarUser.setForeground(new java.awt.Color(255, 255, 255));
        btn_validarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/verified17.png"))); // NOI18N
        btn_validarUser.setText("Validar");
        btn_validarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_backLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_Bienvenido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btn_validarUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panel_backLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(label_Bienvenido1)
                .addGap(18, 18, 18)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_validarUser)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_validarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validarUserActionPerformed
        
        
        jDLogin_password.setResizable(false);
        jDLogin_password.setLocationRelativeTo(null);
        jDLogin_password.setVisible(true);
        jDLogin_password.setSize(338, 480);
        jDLogin_password.setVisible(true);
    }//GEN-LAST:event_btn_validarUserActionPerformed

    private void btn_validarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validarPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_validarPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_validarPassword;
    private javax.swing.JButton btn_validarUser;
    private javax.swing.JDialog jDLogin_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel label_Bienvenido;
    private javax.swing.JLabel label_Bienvenido1;
    private javax.swing.JLabel label_BienvenidoEmpelado;
    private javax.swing.JLabel label_image;
    private javax.swing.JLabel label_image1;
    private javax.swing.JLabel label_pass;
    private javax.swing.JPanel panel_backLogo;
    private javax.swing.JPanel panel_backLogo1;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
