/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author ByteDrive
 */
public class JFRootHome extends javax.swing.JFrame {
    /**
     * Creates new form JFSettingsDB
     */
    public JFRootHome() {
        initComponents();
        settingsFrame();
    }
      private void settingsFrame(){
            //Configuraciones frame
            this.setResizable(false);
            this.setLocationRelativeTo(null);
            this.setVisible(true);
            this.setSize(668, 424);
            this.getContentPane().setBackground(Color.black);
            //Set imageIcon logo CARSHOP
            
            ImageIcon imageLogo = new ImageIcon(getClass().getResource("/ASSETS/LogoCARSHOP.png"));
            label_image.setIcon(new ImageIcon(imageLogo.getImage().getScaledInstance(label_image.getWidth(),label_image.getHeight(),Image.SCALE_SMOOTH)));
           
            //Set image in background panel
            JLabel backImage = new JLabel("");
            ImageIcon image = new ImageIcon(getClass().getResource("/ASSETS/carrr.jpg"));
            panel_image.add(backImage);
            backImage.setIcon(new ImageIcon(image.getImage().getScaledInstance(panel_image.getWidth()+21,panel_image.getHeight(),Image.SCALE_SMOOTH)));
            backImage.setSize(panel_image.getWidth()+21,panel_image.getHeight());
            backImage.setLocation(0,0);
            //Opacity: set alpha for panels 
            Color colorBlack = new Color(0,0,0,190);
            panel_addGerente.setBackground(colorBlack);
            panel_ConfiguracionBD.setBackground(colorBlack);
            //Setings tabedPane
            Color color = new Color(255,255,255,200);
            jPanelbackground.setBackground(color);
            //Set icons in labels btn
            Image settBDIcon = new ImageIcon(getClass().getResource("/ASSETS/settBD.png")).getImage().getScaledInstance(80,80,Image.SCALE_SMOOTH);
            Image jefeIcon = new ImageIcon(getClass().getResource("/ASSETS/jefe.png")).getImage().getScaledInstance(120,100,Image.SCALE_SMOOTH);

            
             btn_addGerente.setIcon(new ImageIcon(jefeIcon));
             btn_configBD.setIcon(new ImageIcon(settBDIcon));

            JLabel lsettBD = new JLabel("Configuracion BD",SwingConstants.CENTER);
            lsettBD.setForeground(Color.white);
            lsettBD.setFont(new Font("Gulim",Font.PLAIN, 16));
            panel_ConfiguracionBD.add(lsettBD);
            lsettBD.setSize(panel_ConfiguracionBD.getWidth(), 50);
            lsettBD.setLocation(0,120);

            JLabel lgerente = new JLabel("Agregar gerente",SwingConstants.CENTER);
            lgerente.setForeground(Color.white);
            lgerente.setFont(new Font("Gulim",Font.PLAIN, 16));
            panel_addGerente.add(lgerente);
            lgerente.setSize(panel_addGerente.getWidth(), 50);
            lgerente.setLocation(0,120);

             
            //Cambiar icono
            Image icon = Toolkit.getDefaultToolkit().getImage("/ASSETS/LogoCARSHOP.png");
            this.setIconImage(icon);
            //Settings backpanel
            
         //Settings in dialog
          dialog_settingBD.setSize(517, 330);
          dialog_settingBD.setResizable(false);
          dialog_settingBD.setLocationRelativeTo(null);
         
          Color colorb = new Color(255,255,255,130);
          panel_backDialog.setBackground(colorb);
          //Set image in background panel
            JLabel backImage2 = new JLabel("");
            ImageIcon image2 = new ImageIcon(getClass().getResource("/ASSETS/carrr.jpg"));
            panel_imgDialog.setSize(517,360);
            panel_imgDialog.add(backImage2);
            backImage2.setIcon(new ImageIcon(image.getImage().getScaledInstance(panel_imgDialog.getWidth()+21,panel_imgDialog.getHeight(),Image.SCALE_SMOOTH)));
            backImage2.setSize(panel_imgDialog.getWidth()+21,panel_imgDialog.getHeight());
            backImage2.setLocation(0,0);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_settingBD = new javax.swing.JDialog();
        panel_imgDialog = new javax.swing.JPanel();
        panel_backDialog = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUSERNAME = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPASSWORD = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPORT = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btn_guardarBD = new javax.swing.JLabel();
        label_image = new javax.swing.JLabel();
        label_usuario = new javax.swing.JLabel();
        btn_settings = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        panel_image = new javax.swing.JPanel();
        jPanelbackground = new javax.swing.JPanel();
        panel_addGerente = new javax.swing.JPanel();
        btn_addGerente = new javax.swing.JLabel();
        panel_ConfiguracionBD = new javax.swing.JPanel();
        btn_configBD = new javax.swing.JLabel();

        dialog_settingBD.setModal(true);

        jLabel5.setFont(new java.awt.Font("Neou", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Configuración base de datos");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel17.setText("USERNAME:");

        jLabel18.setText("PASSWORD:");

        jLabel19.setText("IP:");

        jLabel20.setText("PORT:");

        btn_guardarBD.setBackground(new java.awt.Color(84, 222, 66));
        btn_guardarBD.setFont(new java.awt.Font("Gulim", 0, 17)); // NOI18N
        btn_guardarBD.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardarBD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_guardarBD.setText("Guardar");
        btn_guardarBD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardarBD.setOpaque(true);

        javax.swing.GroupLayout panel_backDialogLayout = new javax.swing.GroupLayout(panel_backDialog);
        panel_backDialog.setLayout(panel_backDialogLayout);
        panel_backDialogLayout.setHorizontalGroup(
            panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_backDialogLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backDialogLayout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backDialogLayout.createSequentialGroup()
                                .addGroup(panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel18)))
                                .addGap(29, 29, 29)
                                .addGroup(panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPORT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(137, 137, 137))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backDialogLayout.createSequentialGroup()
                                .addGroup(panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_guardarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))))))
        );
        panel_backDialogLayout.setVerticalGroup(
            panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_backDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtPORT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_guardarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_imgDialogLayout = new javax.swing.GroupLayout(panel_imgDialog);
        panel_imgDialog.setLayout(panel_imgDialogLayout);
        panel_imgDialogLayout.setHorizontalGroup(
            panel_imgDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imgDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_backDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_imgDialogLayout.setVerticalGroup(
            panel_imgDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imgDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_backDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dialog_settingBDLayout = new javax.swing.GroupLayout(dialog_settingBD.getContentPane());
        dialog_settingBD.getContentPane().setLayout(dialog_settingBDLayout);
        dialog_settingBDLayout.setHorizontalGroup(
            dialog_settingBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_imgDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialog_settingBDLayout.setVerticalGroup(
            dialog_settingBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_imgDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CARSHOP: ROOT");

        label_usuario.setFont(new java.awt.Font("Neou", 0, 13)); // NOI18N
        label_usuario.setForeground(new java.awt.Color(255, 255, 255));
        label_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario.setText("Usuario: pedro@carshop");

        btn_settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/gears10(1).png"))); // NOI18N
        btn_settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/power96(1).png"))); // NOI18N
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_addGerente.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        btn_addGerente.setForeground(new java.awt.Color(255, 255, 255));
        btn_addGerente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_addGerente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_addGerente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panel_addGerenteLayout = new javax.swing.GroupLayout(panel_addGerente);
        panel_addGerente.setLayout(panel_addGerenteLayout);
        panel_addGerenteLayout.setHorizontalGroup(
            panel_addGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addGerenteLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btn_addGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        panel_addGerenteLayout.setVerticalGroup(
            panel_addGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addGerenteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_addGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        btn_configBD.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        btn_configBD.setForeground(new java.awt.Color(255, 255, 255));
        btn_configBD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_configBD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_configBD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panel_ConfiguracionBDLayout = new javax.swing.GroupLayout(panel_ConfiguracionBD);
        panel_ConfiguracionBD.setLayout(panel_ConfiguracionBDLayout);
        panel_ConfiguracionBDLayout.setHorizontalGroup(
            panel_ConfiguracionBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ConfiguracionBDLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_configBD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panel_ConfiguracionBDLayout.setVerticalGroup(
            panel_ConfiguracionBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ConfiguracionBDLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btn_configBD, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanelbackgroundLayout = new javax.swing.GroupLayout(jPanelbackground);
        jPanelbackground.setLayout(jPanelbackgroundLayout);
        jPanelbackgroundLayout.setHorizontalGroup(
            jPanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbackgroundLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(panel_ConfiguracionBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_addGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanelbackgroundLayout.setVerticalGroup(
            jPanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbackgroundLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_addGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_ConfiguracionBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout panel_imageLayout = new javax.swing.GroupLayout(panel_image);
        panel_image.setLayout(panel_imageLayout);
        panel_imageLayout.setHorizontalGroup(
            panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_imageLayout.setVerticalGroup(
            panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_logout)
                    .addComponent(btn_settings))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_usuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRootHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRootHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRootHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRootHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRootHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_addGerente;
    public javax.swing.JLabel btn_configBD;
    public javax.swing.JLabel btn_guardarBD;
    public javax.swing.JLabel btn_logout;
    public javax.swing.JLabel btn_settings;
    public javax.swing.JDialog dialog_settingBD;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelbackground;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_image;
    public javax.swing.JLabel label_usuario;
    private javax.swing.JPanel panel_ConfiguracionBD;
    private javax.swing.JPanel panel_addGerente;
    public javax.swing.JPanel panel_backDialog;
    private javax.swing.JPanel panel_image;
    private javax.swing.JPanel panel_imgDialog;
    public javax.swing.JTextField txtIP;
    public javax.swing.JTextField txtPASSWORD;
    public javax.swing.JTextField txtPORT;
    public javax.swing.JTextField txtUSERNAME;
    // End of variables declaration//GEN-END:variables
}
